sudo: required

language: bash

services:
  - docker

branches:
  only:
    - master
    - develop

install:
  - docker build . -t myownportfolio-editor

script:
  - docker run --name build_web --volume /root/web:/root/dist/app myownportfolio-editor npm run build:web
  - docker run --name build_electron --volume /root/electron:/root/dist/package myownportfolio-editor npm run build:electron

deploy:
  provider: surge
  project: /root/web/
  domain: editor.myownportfolio.surge.sh
  on: develop
