sudo: required

language: bash

services:
  - docker

branches:
  only:
    - master

install:
  - docker build . -t myownportfolio-editor

script:
  - docker run --rm --volume $(pwd)/web:/root/dist/app myownportfolio-editor npm run test
  - docker run --rm --volume $(pwd)/web:/root/dist/app myownportfolio-editor npm run build:web
  - docker run --rm --volume $(pwd)/electron:/root/dist/package myownportfolio-editor npm run build:electron

deploy:
  provider: surge
  domain: editor.myownportfolio.surge.sh
  skip_cleanup: true
