sudo: required

language: bash

services:
  - docker

branches:
  only:
    - master
    - develop

install:
  - docker build . -t myownportfolio-editor

script:
  - docker run --name build_web --volume ${pwd}/web:/root/dist/app myownportfolio-editor npm run build:web
  - docker run --name build_electron --volume ${pwd}/electron:/root/dist/package myownportfolio-editor npm run build:electron
  - pwd
  - ls -al ${pwd}/web/

deploy:
  provider: surge
  project: ${pwd}/web/
  domain: editor.myownportfolio.surge.sh
  on: develop
